version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.8.1
    ports:
      - 9200:9200
    environment:
      discovery.type: 'single-node'
      discovery.seed_hosts: "localhost:9200"
      xpack.security.enabled: 'false'
      ELASTIC_PASSWORD: 'test_elastic'
      ES_JAVA_OPTS: '-Xmx2g -Xms2g'
      ES_PORT: 127.0.0.1:9200